#!/bin/bash
# CloudPipe Monitoring Setup
# Uses UptimeRobot (free) to monitor your Railway deployment

echo "======================================"
echo "  CloudPipe Monitoring Setup Guide"
echo "======================================"
echo ""
echo "1. Go to https://uptimerobot.com and create a free account"
echo ""
echo "2. Click 'Add New Monitor'"
echo "   - Monitor Type: HTTP(s)"
echo "   - Friendly Name: CloudPipe API"
echo "   - URL: https://your-railway-url.railway.app/"
echo "   - Monitoring Interval: Every 5 minutes (free plan)"
echo ""
echo "3. Add more monitors for key endpoints:"
echo "   - https://your-railway-url.railway.app/info"
echo "   - https://your-railway-url.railway.app/metrics"
echo ""
echo "4. Set up email alerts for downtime"
echo ""
echo "======================================"
echo "  Free Monitoring Features:"
echo "======================================"
echo "  ✅ 50 monitors free"
echo "  ✅ 5-minute check intervals"
echo "  ✅ Email/SMS alerts"
echo "  ✅ Public status page"
echo "  ✅ Response time tracking"
echo ""
echo "Replace 'your-railway-url' with your actual Railway URL"
